### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by virusidentifier** [pbatard/winpatch#7]
This is a trojan you dickhead... fuck off trying to give people viruses...

**Comment by pbatard** [comment]
See #6. It should be __EXCEEDINGLY SIMPLE__ to demonstrate if winpatch is a Trojan.

If you can't do that, then please educate yourself about [false positives](https://en.wikipedia.org/wiki/False_positives_and_false_negatives).

Oh, and the only thing insulting people grants you is an automatic block.
