### ISSUE TITLE
Won't Run

### ISSUE THREAD

**Issue by FarrDickson** [pbatard/winpatch#9]
I have tried downloading the file, extracting the zip, and running it as an administrator several times and it only opens for a millisecond. I tried restarting my computer and re-downloading but to no avail. When troubleshooting it said I needed windows 8? I was wondering if you had any inspiration to help me to get this to work. I am trying to patch my windows download onto my raspberry pi 4.

**Comment by Biswa96** [comment]
Open it in a shell, like Command Prompt or Powershell.

**Comment by pbatard** [comment]
Yes, as the very first line of the readme indicates, this is a commandline utility, and not something you simply double click on and that does everything for you. You need to **manually type** a set of parameters, from a command prompt, and then winpatch will report something to indicate whether it worked or not, as per the screenshot below:

![screenshot](https://raw.githubusercontent.com/pbatard/winpatch/master/pics/Screenshot.png)

**Comment by FarrDickson** [comment]
It doesn't show up in my directory in my Command prompt.
